language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

sudo: false

before_install:
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit
